Documento de introspecção
UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS pull request #17
Opened 2021-02-16 15:40 UTC by marcelog5

# Criação de novo documento

## Descrição 
Cria o documento de introspecção para o projeto

[Criação documento de elicitação por introspecção](https://github.com/UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS/issues/16)

## Porque este Pull Request é necessário?
Para elicitar requisitos utilizando a técnica de introspecção

## Critérios de aceitação

1. [x] O documento contempla o seu objetivo?
2. [x] O documento está escrito de forma concisa?
3. [x] A ortografia do documento está correta?
4. [x] O documento possui links para as personas?
5. [x] Os requisitos estão escritos no padrão definido?
6. [x] Os requisitos possuem tipos (funcionais, não funcionais)?
7. [x] Os requisitos possuem as personas relacionadas?

Resolve #16

2021-02-16 15:59 UTC, Rhuancpq requested changes
Mudar os links para o léxico

2021-02-16 15:59 UTC, Rhuancpq commented on docs/requisitos/introspeccao.md
> +<td>O sistema funcionar em <i>smartphones</i></td>
O sistema deve funcionar

2021-02-16 15:59 UTC, Rhuancpq commented on docs/requisitos/introspeccao.md
> +<td>O vendedor deve ser capaz de remover um anúncio</td>
Faltou linkar aqui

2021-02-16 15:59 UTC, Rhuancpq commented on docs/requisitos/introspeccao.md
> +<td>O sistema deverá notificar o usuário quando um anúncio que ele reportou for invalidado</td>
Lexico - anuncio

2021-02-16 15:59 UTC, Rhuancpq commented on docs/requisitos/introspeccao.md
> +<td>O sistema deve listar apenas anúncios válidos</td>
Léxico anuncios validos

2021-02-17 03:31 UTC, WashingtonBispo approved these changes
Certo demais

2021-02-17 03:39 UTC, Rhuancpq approved these changes

2021-02-17 03:40 UTC, merged