Adição do diagrama de classes
UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS pull request #61
Opened 2021-02-25 23:16 UTC by marcelog5

# Criação de novo documento

## Descrição 
Criar um documento contendo o diagrama de classes do sistema proposto

[Criação do Documento de Diagrama de Classes](https://github.com/UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS/issues/53)

## Porque este Pull Request é necessário?
Para adicionar o diagrama de classes ao projeto

## Critérios de aceitação

1. [x] O documento contempla o seu objetivo?
2. [x] O documento está escrito de forma concisa?
3. [x] A ortografia do documento está correta?
4. [x] Há referências bibliográficas? Elas estão escritas no padrão correto?
5. [x] O documento está devidamente versionado?
6. [x] O diagrama contempla todas as informações necessárias?
7. [x] Todas as classes do diagrama estão devidamente especificadas?
8. [x] O diagrama obedece o padrão UML?
9. [x] Todos os métodos estão explícitos?
10. [x] O documento foi revisado pelos integrantes do grupo?

Resolve #53

2021-02-26 11:21 UTC, igor-paiva requested changes

2021-02-26 11:21 UTC, igor-paiva commented on docs/diagrama_classes.md
> +> https://www.lucidchart.com/pages/uml-class-diagram
Faltou: Título, disponível em e acesso em.

2021-02-26 11:21 UTC, igor-paiva commented on docs/diagrama_classes.md
> +![Diagrama de classes](assets/diagrama_classes/Diagrama_de_classes.png)
Acho legal a gente colocar um iframe pro diagrama no lucidchart, fica melhor a visualização

2021-03-01 15:11 UTC, thiagolopess commented on docs/diagrama_classes.md
> +![Diagrama de classes](assets/diagrama_classes/Diagrama_de_classes.png)
Done!

2021-03-01 15:11 UTC, thiagolopess commented on docs/diagrama_classes.md
> +> https://www.lucidchart.com/pages/uml-class-diagram
Done!

2021-03-01 15:12 UTC, thiagolopess approved these changes
Corrigido e aprovado!

2021-03-01 22:35 UTC, ThiagoGMF approved these changes

2021-03-01 23:31 UTC, igor-paiva approved these changes

2021-03-01 23:31 UTC, igor-paiva commented on docs/diagrama_classes.md
> +<div style="width: 960px; height: 720px; margin: 10px; position: relative;"><iframe allowfullscreen frameborder="0" style="width:960px; height:720px" src="https://lucid.app/documents/embeddedchart/93
Iframe não está mostrando o diagrama

2021-03-02 00:47 UTC, merged