Criação do documento de componentes
UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS pull request #65
Opened 2021-03-02 22:53 UTC by Rhuancpq

# Criação do documento de componentes

## Descrição 
Adiciona o diagrama de componentes a wiki

[Criação do documento de diagrama de componentes ](https://github.com/UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS/issues/64)

## Porque este Pull Request é necessário?
Para que o diagrama de componentes possa ser visualizado e documentado

## Critérios de aceitação

1. [x] O documento contempla o seu objetivo?
2. [x] O documento está escrito de forma concisa?
3. [x] A ortografia do documento está correta?
4. [x] Há referências bibliográficas? Elas estão escritas no padrão correto?
5. [x] O documento está devidamente versionado?
6. [x]  O diagrama obedece o padrão UML?
7. [x] O documento foi revisado por todos os integrantes do grupo?

Resolve #(64)

2021-03-02 23:43 UTC, marcelog5 approved these changes

2021-03-03 15:55 UTC, ThiagoGMF requested changes

2021-03-03 15:55 UTC, ThiagoGMF commented on docs/diagrama_componentes.md
> +# Diagrama de classes
Titulo errado

2021-03-03 16:00 UTC, ThiagoGMF approved these changes

2021-03-03 16:00 UTC, merged