Atualização do documento de padrões de documento e versões
UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS pull request #74
Opened 2021-03-05 12:35 UTC by Rhuancpq

# Atualização do documento de padrões de documento e versões

## Descrição 
Atualiza o documento de padrões de documento e versões

## Porque este Pull Request é necessário?
Atualiza os padrões pare que fiquem adequados com o que utilizaremos

## Critérios de aceitação

1. [ ] Todas as informações necessárias estão presentes?
2. [ ] O documento está escrito de forma concisa?
3. [ ] A ortografia do documento está correta?
4. [ ] Os novos padrões ficaram concisos?

2021-03-05 16:22 UTC, ThiagoGMF approved these changes

2021-03-05 16:23 UTC, WashingtonBispo approved these changes
Tudo certo

2021-03-05 16:25 UTC, igor-paiva commented
A gente devia documentar no documento de padrão de documento para adicionar um tópico de palavras chaves para colocar as palavras usadas naquele documento e linkar elas com o documento de léxicos

2021-03-07 01:25 UTC, igor-paiva requested changes

2021-03-07 01:25 UTC, igor-paiva commented on docs/padroes/documento.md
>  ## Referências
A gente devia documentar a questão das palavras-chave. Seria uma seção com uma lista de palavras.

Algo do tipo:

```md
## Palavras-chave

&emsp;[Anúncio](/link), [usuário](/link), AlgumaOutraPalavraSemLink.
```

2021-03-07 15:17 UTC, merged